# Generated by Django 3.2.6 on 2021-08-27 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Subcategory',
            new_name='Sub_category',
        ),
    ]
